// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/80060c94ef549c077a011977c2b5461bd0fd8947/electron-devtools-installer/index.d.ts
declare module "electron-devtools-installer" {
    interface ExtensionReference {
        id: string,
        electron: string,
    }

    // Default installation function
    export default function (extensionReference: ExtensionReference | string, forceDownload?: boolean): Promise<string>;

    // Devtools themself
    export const EMBER_INSPECTOR: ExtensionReference;
    export const REACT_DEVELOPER_TOOLS: ExtensionReference;
    export const BACKBONE_DEBUGGER: ExtensionReference;
    export const JQUERY_DEBUGGER: ExtensionReference;
    export const ANGULARJS_BATARANG: ExtensionReference;
    export const VUEJS_DEVTOOLS: ExtensionReference;
    export const REDUX_DEVTOOLS: ExtensionReference;
    export const REACT_PERF: ExtensionReference;
}
